

VALUTA_SOLDI='gbp'
VALUTA_CRIPTO='btc'
COPPIA_DA_USARE_NOME=f'{VALUTA_CRIPTO}{VALUTA_SOLDI}'

DATASET_CARTELLA_PERCORSO = 'dataset'

FEE=0.0

FORMATO_DATA_ORA='%d-%m-%Y %H:%M:%S'

LOG_CARTELLA_PERCORSO = 'log'
TRADING_REPORT_FILENAME = "log/report.txt"

PORTAFOGLIO_PERCORSO = 'sorgenti/portafoglio.json'

VALORI_PERCORSO = 'sorgenti/valori.json'
