

VALUTA_SOLDI='gbp'
VALUTA_CRIPTO='btc'
COPPIA_DA_USARE_NOME=f'{VALUTA_CRIPTO}{VALUTA_SOLDI}'

FEE=0.0
MINIMUM_ORDER_VALUE = 25

LUNGHEZZA_MEMORIA = 100
NUMERO_ORDINI_ORDERBOOK = 1



FORMATO_DATA_ORA="%d-%m-%Y %H:%M:%S"
LOG_CARTELLA_PERCORSO = "log"
TRADING_REPORT_FILENAME = "log/report.txt"
STATISTICA_PERCORSO = "log/stats.json"

PORTAFOGLIO_PERCORSO = "sorgenti/portafoglio.json"
VALORI_PERCORSO = "sorgenti/valori.json"
VALORI_TEMPLATE_PERCORSO = "sorgenti/valori_template.json"


BITSTAMP_WEBSOCKET_URL = "wss://ws.bitstamp.net"
BITSTAMP_WEBSOCKET_EVENT = "bts:subscribe"
BITSTAMP_WEBSOCKET_CHANNEL_TRADE = f"live_trades_{COPPIA_DA_USARE_NOME}"
BITSTAMP_WEBSOCKET_CHANNEL_ORDERBOOK = f"order_book_{COPPIA_DA_USARE_NOME}"
WEBSOCKET_AUTORECONNECT = True
WEBSOCKET_AUTORECONNECT_RETRIES = 60